name = "idkaboutbytes/spring"
version = "1.0.2"
description = "Spring package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/spring"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Observable = { repo = "idkaboutbytes/observable", rev = "v1.0.2" }
Blend = { repo = "idkaboutbytes/blend", rev = "v1.0.2" }
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.3" }
DuckTypeUtils = { repo = "idkaboutbytes/ducktypeutils", rev = "v1.0.3" }
Maid = { repo = "idkaboutbytes/maid", rev = "v1.1.2" }
Promise = { repo = "idkaboutbytes/promise", rev = "v2.1.3" }
SpringUtils = { repo = "idkaboutbytes/springutils", rev = "v1.0.2" }
StepUtils = { repo = "idkaboutbytes/steputils", rev = "v1.0.2" }
